# Generated by Django 6.1 on 2026-09-03 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Cartão (Ex: Nubank, Visa)')),
                ('limit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Limite Total')),
                ('due_day', models.PositiveIntegerField(default=10, verbose_name='Dia de Vencimento da Fatura')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição / Produto')),
                ('purchase_date', models.DateField(verbose_name='Data da Compra')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total')),
                ('installments_count', models.PositiveIntegerField(default=1, verbose_name='Quantidade de Parcelas')),
                ('status', models.CharField(default='active', max_length=20, verbose_name='Status')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='credit_cards.creditcard', verbose_name='Cartão de Crédito')),
            ],
        ),
    ]
