# Generated by Django 6.1 on 2026-09-03 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcardexpense',
            name='status',
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='due_day',
            field=models.PositiveIntegerField(default=10, verbose_name='Dia de Vencimento Padrão'),
        ),
        migrations.CreateModel(
            name='MonthlyCardDueOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_ano', models.CharField(max_length=20)),
                ('due_date', models.DateField(verbose_name='Data de Vencimento Específica')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='due_overrides', to='credit_cards.creditcard')),
            ],
            options={
                'unique_together': {('card', 'mes_ano')},
            },
        ),
    ]
