# Generated by Django 6.1 on 2026-08-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cnpj_cpf',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ/CPF'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome do Cliente'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome do Fornecedor'),
        ),
    ]
