# Generated by Django 6.1 on 2026-08-28 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('orders', '0004_alter_purchaseorderitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.salesorder'),
        ),
    ]
