# Generated by Django 6.1 on 2026-08-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_financialrecord_purchase_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='delivery_status',
            field=models.CharField(default='-', max_length=50, verbose_name='Status de Entrega'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago/Recebido'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=15, verbose_name='Status de Pagamento'),
        ),
    ]
