# Generated by Django 6.1 on 2026-08-27 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_product', models.OneToOneField(limit_choices_to={'type': 'FIN'}, on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='BoMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.billofmaterial')),
                ('raw_material', models.ForeignKey(limit_choices_to={'type': 'RAW'}, on_delete=django.db.models.deletion.RESTRICT, to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_to_produce', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('DONE', 'Concluído')], default='PENDING', max_length=10)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='production.billofmaterial')),
            ],
        ),
    ]
