# Generated by Django 6.1 on 2026-08-27 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=10)),
                ('movement_type', models.CharField(choices=[('IN', 'Entrada (Compra)'), ('OUT', 'Saída (Venda)'), ('PROD_IN', 'Entrada (Produção)'), ('PROD_OUT', 'Consumo (Produção)'), ('ADJ', 'Ajuste de Inventário')], max_length=15)),
                ('description', models.CharField(blank=True, help_text='Ex: Ordem de Produção #1, Nota Fiscal #123', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product')),
            ],
        ),
    ]
