# Generated by Django 6.1 on 2026-08-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
