# Generated by Django 6.1 on 2026-08-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stockmovement_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reorder_point',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ponto de Reposição'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Quantidade em Estoque'),
        ),
    ]
