# Generated by Django 6.1 on 2026-08-27 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0003_alter_stockmovement_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEEDED', 'Necessário (Sugestão)'), ('OPEN', 'Em Aberto (Aguardando Entrega)'), ('COMPLETED', 'Concluído (Recebido)'), ('CANCELED', 'Cancelado')], default='NEEDED', max_length=20)),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Data de Colocação')),
                ('receipt_date', models.DateField(blank=True, null=True, verbose_name='Data de Recebimento')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Total')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('stock_received', models.BooleanField(default=False, editable=False)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.supplier', verbose_name='Fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.purchaseorder')),
                ('product', models.ForeignKey(limit_choices_to={'type': 'RAW'}, on_delete=django.db.models.deletion.RESTRICT, to='inventory.product')),
            ],
        ),
    ]
