# Generated by Django 6.1 on 2026-08-27 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer'),
        ('inventory', '0003_alter_stockmovement_description'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('QUOTATION', 'Orçamento'), ('OPEN', 'Em Aberto (Aguardando Envio)'), ('COMPLETED', 'Concluído (Entregue)'), ('CANCELED', 'Cancelado')], default='QUOTATION', max_length=20)),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Data de Entrega')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Total')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('stock_deducted', models.BooleanField(default=False, editable=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.customer', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.salesorder')),
                ('product', models.ForeignKey(limit_choices_to={'type': 'FIN'}, on_delete=django.db.models.deletion.RESTRICT, to='inventory.product')),
            ],
        ),
    ]
