# Generated by Django 6.1 on 2026-08-28 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_salesorder_salesorderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField(verbose_name='Número da Parcela')),
                ('due_date', models.DateField(verbose_name='Data de Pagamento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Parcela')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='orders.purchaseorder', verbose_name='Pedido de Compra')),
            ],
        ),
        migrations.CreateModel(
            name='SalesInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField(verbose_name='Número da Parcela')),
                ('due_date', models.DateField(verbose_name='Data de Recebimento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Parcela')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='orders.salesorder', verbose_name='Pedido de Venda')),
            ],
        ),
    ]
