# Generated by Django 6.1 on 2026-08-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_purchaseorderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Realizado / Pago'), ('OVERDUE', 'Atrasado'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Status de Pagamento'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Realizado / Pago'), ('OVERDUE', 'Atrasado'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Status de Pagamento'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('NEEDED', 'Necessário (Sugestão)'), ('OPEN', 'Em Aberto (Aguardando Entrega)'), ('COMPLETED', 'Concluído (Recebido)'), ('CANCELED', 'Cancelado')], default='NEEDED', max_length=20, verbose_name='Status de Entrega/Pedido'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('QUOTATION', 'Orçamento'), ('OPEN', 'Em Aberto (Aguardando Envio)'), ('COMPLETED', 'Concluído (Entregue)'), ('CANCELED', 'Cancelado')], default='QUOTATION', max_length=20, verbose_name='Status de Entrega/Pedido'),
        ),
    ]
