# Generated by Django 6.1 on 2026-08-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_purchaseorder_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='purchaseinstallment',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Realizado / Pago'), ('OVERDUE', 'Atrasado'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Status de Pagamento'),
        ),
        migrations.AddField(
            model_name='salesinstallment',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Realizado / Pago'), ('OVERDUE', 'Atrasado'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Status de Pagamento'),
        ),
    ]
